import type { TourStepV1, TourVariant } from '../types';

export const TOUR_CAMPAIGN_ID = 'tour-auth-role-revocation-v1';

export const GUIDED_TOUR_STEPS: TourStepV1[] = [
  {
    id: 'intro',
    chapter: 'INPUT',
    variants: ['guided', 'judge', 'technical', 'explore'],
    surface: 'input',
    title: 'This is GhostRange',
    body: 'GhostRange investigates security incidents by reconstructing the system, creating competing explanations, running controlled experiments in disposable environments, and preserving the evidence.',
  },
  {
    id: 'input-repo',
    chapter: 'INPUT',
    variants: ['guided', 'judge', 'technical'],
    surface: 'input',
    title: 'Start with the system',
    body: 'A GitHub repository gives GhostRange source, service relationships, Dockerfiles, infrastructure manifests, APIs and configuration that help build the initial system model.',
    domAnchor: 'tour-input-repo',
  },
  {
    id: 'input-incident',
    chapter: 'INPUT',
    variants: ['guided', 'judge', 'technical'],
    surface: 'input',
    title: 'Then tell it what happened',
    body: 'The incident describes the observed failure. GhostRange does not treat this description as the cause—it is only the starting observation.',
    domAnchor: 'tour-input-incident',
  },
  {
    id: 'input-evidence',
    chapter: 'INPUT',
    variants: ['guided', 'judge', 'technical'],
    surface: 'input',
    title: 'Evidence makes the twin better',
    body: 'Logs, traces, alerts and runtime information tell GhostRange how the deployed system behaved, which may differ from what the repository says.',
    domAnchor: 'tour-input-evidence',
  },
  {
    id: 'build-investigation',
    chapter: 'INPUT',
    variants: ['guided', 'judge', 'technical'],
    surface: 'input',
    title: 'Build the investigation',
    body: 'GhostRange compiles inputs into a controlled replay campaign. Nothing in this tour creates billable cloud resources.',
    interaction: 'build-investigation',
  },
  {
    id: 'living-twin',
    chapter: 'UNDERSTAND',
    variants: ['guided', 'judge', 'technical'],
    surface: 'scene',
    mode: 'multiverse',
    camera: 'multiverse',
    replayMs: 9000,
    anchor: 'production-world',
    title: 'This is the Living Twin',
    body: "GhostRange reconstructed the important services, dependencies, identity flows and runtime observations into an evolving model of the system.",
    truthLabel: 'DERIVED',
  },
  {
    id: 'select-auth',
    chapter: 'UNDERSTAND',
    variants: ['guided', 'technical'],
    surface: 'scene',
    mode: 'multiverse',
    camera: 'network',
    replayMs: 9000,
    anchor: 'auth-service',
    title: 'Every object is evidence-linked',
    body: 'This is not decorative topology. Components connect to source files, deployment information and runtime observations that caused GhostRange to represent them.',
    interaction: 'select-auth-service',
  },
  {
    id: 'attack-path',
    chapter: 'UNDERSTAND',
    variants: ['guided', 'judge', 'technical'],
    surface: 'scene',
    mode: 'multiverse',
    camera: 'world',
    replayMs: 12000,
    anchor: 'attack-path',
    title: 'This is what was observed',
    body: 'The highlighted path represents incident evidence: revoked privileges still reaching a protected endpoint after session refresh.',
    truthLabel: 'OBSERVED',
  },
  {
    id: 'hypotheses',
    chapter: 'INVESTIGATE',
    variants: ['guided', 'judge', 'technical'],
    surface: 'scene',
    mode: 'multiverse',
    replayMs: 16000,
    anchor: 'hypothesis-branch',
    title: 'GhostRange does not trust its first explanation',
    body: 'GhostDirector creates competing hypotheses instead of committing to a single model-generated diagnosis.',
  },
  {
    id: 'experiment-design',
    chapter: 'INVESTIGATE',
    variants: ['guided', 'technical'],
    surface: 'scene',
    mode: 'multiverse',
    replayMs: 20000,
    title: 'What experiment would distinguish them?',
    body: 'GhostDirector selects experiments based on how much uncertainty they could remove, their cost and whether they can be executed safely.',
  },
  {
    id: 'select-experiment',
    chapter: 'INVESTIGATE',
    variants: ['guided', 'technical'],
    surface: 'scene',
    mode: 'execution',
    camera: 'execution',
    replayMs: 30000,
    anchor: 'execution-dag',
    interaction: 'select-cache-experiment',
    title: 'Select the discriminating experiment task',
    body: 'Select the running verification task in the execution graph. It represents the controlled experiment that can separate stale-cache from session-refresh hypotheses.',
  },
  {
    id: 'experiments-not-guesses',
    chapter: 'INVESTIGATE',
    variants: ['guided', 'judge', 'technical'],
    surface: 'scene',
    title: 'This is the key difference',
    body: 'GhostRange does not ask an AI which hypothesis sounds best. It asks which controlled experiment would make the hypotheses behave differently.',
  },
  {
    id: 'execution-dag',
    chapter: 'EXECUTE',
    variants: ['guided', 'judge', 'technical'],
    surface: 'scene',
    mode: 'execution',
    camera: 'execution',
    replayMs: 30000,
    anchor: 'execution-dag',
    title: 'Experiments become an execution graph',
    body: 'GhostScheduler turns approved experiments into tasks, dependencies and resource requirements.',
  },
  {
    id: 'scheduler-decision',
    chapter: 'EXECUTE',
    variants: ['guided', 'judge', 'technical'],
    surface: 'scene',
    mode: 'execution',
    replayMs: 31000,
    anchor: 'scheduler-decision',
    title: 'Compute is a decision, not a default',
    body: 'GhostScheduler evaluates end-to-end completion and cost instead of blindly selecting the fastest hardware.',
    showWhy: true,
  },
  {
    id: 'worker-lifecycle',
    chapter: 'EXECUTE',
    variants: ['guided', 'judge', 'technical'],
    surface: 'scene',
    mode: 'execution',
    replayMs: 28000,
    anchor: 'worker-active',
    title: 'Now GhostRange creates infrastructure',
    body: 'When capacity is insufficient, GhostScheduler can request a temporary Vultr worker. The worker exists only because the experiment requires it.',
    truthLabel: 'CONTROLLED REPLAY',
  },
  {
    id: 'select-worker',
    chapter: 'EXECUTE',
    variants: ['guided', 'judge', 'technical'],
    surface: 'scene',
    mode: 'execution',
    replayMs: 29000,
    interaction: 'select-active-worker',
    title: 'This machine is temporary',
    body: 'The control plane owns the infrastructure lifecycle. The worker does not receive the Vultr administrative API key.',
  },
  {
    id: 'evidence-created',
    chapter: 'VERIFY',
    variants: ['guided', 'technical'],
    surface: 'scene',
    mode: 'execution',
    replayMs: 70000,
    title: 'Execution creates evidence',
    body: 'Results and artifacts survive after the temporary machine disappears. Metadata stays in PostgreSQL; large artifacts go to object storage.',
  },
  {
    id: 'hypothesis-refuted',
    chapter: 'VERIFY',
    variants: ['guided', 'technical'],
    surface: 'scene',
    mode: 'multiverse',
    replayMs: 46000,
    title: 'A hypothesis just failed',
    body: 'Negative results are preserved instead of hidden. Geometry changes because investigation state changed.',
  },
  {
    id: 'causal',
    chapter: 'VERIFY',
    variants: ['guided', 'judge', 'technical'],
    surface: 'scene',
    mode: 'multiverse',
    replayMs: 55000,
    anchor: 'causal-path',
    title: 'Correlation is not enough',
    body: 'GhostCausal asks whether changing a suspected mechanism changes the outcome. Intervention evidence is separate from ordinary association.',
    truthLabel: 'INTERVENTION-SUPPORTED',
  },
  {
    id: 'shield-deny',
    chapter: 'CONTROL',
    variants: ['guided', 'judge', 'technical'],
    surface: 'scene',
    mode: 'execution',
    replayMs: 32000,
    anchor: 'action-gate',
    title: 'The AI does not control infrastructure directly',
    body: 'Every protected action becomes a typed request and passes through GhostShield before reaching the provider. A denied proposal stops here—no provider effect.',
    truthLabel: 'MODEL-PROPOSED → DENIED',
  },
  {
    id: 'runtime-recovery',
    chapter: 'CONTROL',
    variants: ['technical'],
    surface: 'scene',
    mode: 'execution',
    replayMs: 40000,
    title: 'Long investigations survive failure',
    body: 'GhostRuntime checkpoints durable campaign state and reconciles external effects after crashes or network failures.',
  },
  {
    id: 'history',
    chapter: 'VERIFY',
    variants: ['guided', 'technical'],
    surface: 'scene',
    mode: 'multiverse',
    replayMs: 20000,
    title: 'This is the entire investigation history',
    body: 'GhostRange preserves what the system believed, executed and knew at earlier points—not only the final answer.',
  },
  {
    id: 'evidence-mode',
    chapter: 'PROVE',
    variants: ['guided', 'judge', 'technical'],
    surface: 'scene',
    mode: 'evidence',
    replayMs: 85000,
    anchor: 'claim-root',
    title: "This is the investigation's truth layer",
    body: 'Claims, artifacts, counterexamples, causal support, authorization and recovery evidence remain connected by provenance.',
  },
  {
    id: 'select-claim',
    chapter: 'PROVE',
    variants: ['guided', 'technical'],
    surface: 'scene',
    mode: 'evidence',
    replayMs: 85000,
    interaction: 'select-final-claim',
    title: 'Every important claim can be traced backwards',
    body: 'Claim → evidence → task → worker → scheduler decision → experiment → hypothesis → twin revision → source input.',
  },
  {
    id: 'verification-ring',
    chapter: 'PROVE',
    variants: ['guided', 'technical'],
    surface: 'scene',
    mode: 'evidence',
    replayMs: 85000,
    anchor: 'verification-ring',
    title: 'Verification has a precise meaning',
    body: 'The ring closes only when configured verification conditions were satisfied—not universal security.',
    truthLabel: 'VERIFIED',
  },
  {
    id: 'arena',
    chapter: 'PROVE',
    variants: ['technical'],
    surface: 'scene',
    mode: 'evidence',
    replayMs: 88000,
    title: 'GhostRange does not grade its own homework',
    body: 'GhostArena evaluates candidates on held-out scenarios that GhostEvolve cannot inspect or train on.',
  },
  {
    id: 'teardown',
    chapter: 'PROVE',
    variants: ['guided', 'judge', 'technical'],
    surface: 'scene',
    mode: 'execution',
    replayMs: 88000,
    title: 'Temporary infrastructure disappears',
    body: 'Workers drain and terminate when work completes. Evidence remains. Final worker count returns to zero in this replay.',
    truthLabel: 'CONTROLLED REPLAY',
  },
  {
    id: 'summary',
    chapter: 'PROVE',
    variants: ['guided', 'judge', 'technical', 'explore'],
    surface: 'summary',
    title: 'The investigation is complete',
    body: 'GhostRange does not ask an AI what went wrong and trust the answer. It builds worlds, runs experiments, tries to disprove its conclusions, and shows you the evidence.',
  },
];

export function stepsForVariant(variant: TourVariant): TourStepV1[] {
  return GUIDED_TOUR_STEPS.filter((s) => s.variants.includes(variant));
}

export function chapterProgress(current: TourStepV1['chapter']) {
  const order: TourStepV1['chapter'][] = [
    'INPUT',
    'UNDERSTAND',
    'INVESTIGATE',
    'EXECUTE',
    'VERIFY',
    'CONTROL',
    'PROVE',
  ];
  const cur = order.indexOf(current);
  return order.map((ch, i) => ({
    id: ch,
    done: i < cur,
    active: i === cur,
  }));
}
